apiVersion: v1
kind: Plugin
metadata:
  author: BiFangKNT
  name: ElysianRealmAssistant
  repository: "https://github.com/BiFangKNT/QChatGPT_ElysianRealmAssistant"
  version: 1.7.0
  description:
    en_US: Honkai Impact 3rd Elysian Realm guide assistant
    zh_Hans: 崩坏3往世乐土攻略助手
  label:
    en_US: ElysianRealmAssistant
    zh_Hans: 往世乐土攻略助手
spec:
  config: []
  components:
    EventListener:
      fromDirs:
        - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: ElysianRealmAssistant
