[project]
name = "langbot-elysianrealmassistant"
version = "1.7.0"
authors = [
    { name = "BiFangKNT" }
]
description = "崩坏3往世乐土攻略助手"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "regex>=2025.9.1",
    "requests>=2.32.5",
]
