from collections.abc import Callable
from typing import Any, TypeVar

_T = TypeVar("_T")

class _Logger:
    def debug(self, message: object, *args: object, **kwargs: object) -> None: ...
    def error(self, message: object, *args: object, **kwargs: object) -> None: ...
    def info(self, message: object, *args: object, **kwargs: object) -> None: ...
    def warning(self, message: object, *args: object, **kwargs: object) -> None: ...

class APIHost:
    logger: _Logger

class BasePlugin:
    ap: APIHost

    def __init__(self, host: APIHost) -> None: ...

class _Event:
    text_message: str

class EventContext:
    event: _Event

    def add_return(self, name: str, value: Any) -> None: ...
    def prevent_default(self) -> None: ...
    def prevent_postorder(self) -> None: ...
    async def reply(self, message: Any) -> Any: ...

def handler(event_type: type[Any]) -> Callable[[_T], _T]: ...
def llm_func(*args: Any, **kwargs: Any) -> Callable[[_T], _T]: ...
def register(*args: Any, **kwargs: Any) -> Callable[[_T], _T]: ...
